kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nacos-9wpmlt
  namespace: nacos
  labels:
    app: nacos
    app.kubernetes.io/managed-by: Helm
    app.kubesphere.io/instance: nacos-9wpmlt
    chart: nacos-2.0.0
    heritage: Helm
    release: nacos-9wpmlt
  annotations:
    kubesphere.io/creator: admin
    meta.helm.sh/release-name: nacos-9wpmlt
    meta.helm.sh/release-namespace: nacos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nacos
      release: nacos-9wpmlt
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nacos
        release: nacos-9wpmlt
      annotations:
        kubesphere.io/creator: admin
        pod.alpha.kubernetes.io/initialized: 'true'
    spec:
      initContainers:
        - name: peer-finder-plugin-install
          image: 'nacos/nacos-peer-finder-plugin:latest'
          resources: {}
          volumeMounts:
            - name: data-storage
              mountPath: /home/nacos/plugins
              subPath: plugins
            - name: data-storage
              mountPath: /home/nacos/data
              subPath: data
            - name: data-storage
              mountPath: /home/nacos/logs
              subPath: logs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: import-nacos-mysql-sql
          image: 'ygqygq2/mysql-exec-sql:latest'
          env:
            - name: SQL_FILES
              valueFrom:
                configMapKeyRef:
                  name: nacos-9wpmlt
                  key: sql_files
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlMasterHost
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlDatabase
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlMasterPort
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlMasterUser
            - name: MYSQL_PASSWD
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlMasterPassword
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      containers:
        - name: nacos
          image: 'docker.io/nacos/nacos-server:v2.0.4'
          ports:
            - name: http
              containerPort: 8848
              protocol: TCP
          env:
            - name: NACOS_REPLICAS
              value: '3'
            - name: NACOS_SERVERS
              value: >-
                nacos-9wpmlt-0.nacos-9wpmlt-headless:8848
                nacos-9wpmlt-1.nacos-9wpmlt-headless:8848
                nacos-9wpmlt-2.nacos-9wpmlt-headless:8848
            - name: DOMAIN_NAME
              value: cluster.local
            - name: SERVICE_NAME
              value: nacos-9wpmlt-headless
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlMasterHost
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlDatabase
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlMasterPort
            - name: MYSQL_SERVICE_USER
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlMasterUser
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nacos-9wpmlt
                  key: mysqlMasterPassword
            - name: NACOS_SERVER_PORT
              value: '8848'
            - name: NACOS_APPLICATION_PORT
              value: '8848'
            - name: PREFER_HOST_MODE
              value: hostname
          resources: {}
          volumeMounts:
            - name: data-storage
              mountPath: /home/nacos/plugins
              subPath: plugins
            - name: data-storage
              mountPath: /home/nacos/data
              subPath: data
            - name: data-storage
              mountPath: /home/nacos/logs
              subPath: logs
          livenessProbe:
            httpGet:
              path: /nacos/v1/console/health/liveness
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /nacos/v1/console/health/readiness
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data-storage
        creationTimestamp: null
        labels:
          app: nacos
          chart: nacos-2.0.0
          heritage: Helm
          release: nacos-9wpmlt
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: csi-disk
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: nacos-9wpmlt-headless
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
